var cart_list = []
        var img_list = ['rice.jpg','beans.webp','potatoes.webp','yam.jpg']
        var img_alt = ['Rice', 'Beans', 'Potatoes', 'Yam']
        var img_price = ['80000', '100000', '30000', '20000',]
        var a = 0;
        var b = 1;
        var c = 2;
        const product_name = document.getElementById('product_name');
        const quantity = document.getElementById('quantity');
        const quantity_num= document.getElementById('quantity_num')
        quantity_num.value = 1
        const size = document.getElementById('size')
        const product_selection = document.getElementById('product_selection');
        const img = document.querySelectorAll('.div img');
        const img1 = document.getElementById('img1');
        const img2 = document.getElementById('img2')
        const img3 = document.getElementById('img3')
        const div = document.getElementById('divcop')
        const div2 = document.getElementById('div2')
        const div_upp = document.getElementById('div_upp')
        const button2 = document.getElementById('button2')
        const button = document.getElementById('button');
        const button1 = document.getElementById('button1');
        const click_name = document.getElementById('click_name');
        const click_quantity =  document.getElementById('click_quantity');
        const price = document.getElementById('price')
        const img1_price = document.getElementById('img1_price');
        const img1_name = document.getElementById('img1_name');
        const img2_price = document.getElementById('img2_price');
        const div_img2 = document.getElementById('div_img2');
        const img2_name = document.getElementById('img2_name');
        const img3_price = document.getElementById('img3_price');
        const img3_name = document.getElementById('img3_name');
        const continue1 = document.getElementById('continue');
        var counting_num = 0;
        var poll ='';
        continue1.style.display = 'none';
        const click_size = document.getElementById('click_size')
      